# Generated by Django 5.0.6 on 2024-06-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
    ]
